version: "3.5"
services:
  proxy:
    build: .
    restart: unless-stopped
    command: "./proxy"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  web:
    build: .
    restart: unless-stopped
    command: "./web"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - proxy

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5436:5432"
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s