postgres_db:
    user: "postgres"
    password: "password"
    host: "localhost"
    #host: "postgres"
    port: "5437"
    dbname: "postgres"
    sslmode: "disable"

proxy:
    #host: "proxy"
    host: "localhost"
    port: "8080"


